Rename package.json to clib.json
Immediate-Mode-UI/Nuklear pull request #365
Opened 2021-11-15 22:13 UTC by Aloz1

The clib package manager has deprecated package.json in favor of clib.json (probably to reduce confusion between clib and other package managers, e.g. npm). As far as I can tell, there's no difference in file format, only in name.

2021-11-15 22:20 UTC, Aloz1 commented
Note, it seems that irrespective of this change, acquiring nukular via clib is currently broken.

It seems that clib now expects a tag to exist for the version specified in package.json/clib.json.

PR #287 will need to be merged to un-break clib support.

2021-12-14 02:41 UTC, RobLoach approved these changes
Seems appropriate.

2021-12-14 08:22 UTC, dumblob commented
Yep, to me too. I wouldn't bump the version as it's only repository-related and not Nuklear (the library/code) related. What do you think?

E.g. if you have a counter example (because of some build tool or whatever dependency), then I'm fine merging this with the bump :wink:.

2021-12-14 09:52 UTC, RobLoach requested changes
Removing the version bump in clib.json

2021-12-14 09:52 UTC, RobLoach commented on src/CHANGELOG
> +/// - 2021/11/16 (4.09.1) - Renamed package.json to clib.json
``` suggestion
```

2021-12-14 09:52 UTC, RobLoach commented on clib.json
> +  "version": "4.09.1",
``` suggestion
  "version": "4.09.0",
```

2021-12-14 22:25 UTC, Aloz1 commented
No counter examples or objections. Have reverted version bump in 8052d27.

2021-12-14 22:25 UTC, Aloz1 commented on clib.json
> +  "version": "4.09.1",
Fixed in 8052d27

2021-12-14 22:25 UTC, Aloz1 commented on src/CHANGELOG
> +/// - 2021/11/16 (4.09.1) - Renamed package.json to clib.json
Fixed in 8052d27

2021-12-14 23:34 UTC, RobLoach commented on Readme.md
> +* Ensure that the contributer has bumped the appropriate version in
``` suggestion
* Ensure that the contributor has bumped the appropriate version in
```

2021-12-14 23:36 UTC, merged