Fix button text alignment error.
Immediate-Mode-UI/Nuklear pull request #586
Opened 2023-11-14 05:46 UTC by mackron

When calculating the width and height of the content rect of a button, only the border of one side is being taken into account. Instead the border width needs to be multiplied by two before subtracting from the bounds. This is being done for padding and rounding, but not border, which is resulting in text being misaligned. The screenshots below demonstrate the issue (I've exaggerated the borders to make it easier to see the effect).

Before:
![image](https://github.com/Immediate-Mode-UI/Nuklear/assets/1232553/24cad65b-905e-445d-bbac-27df2e75a9fa)

After:
![image](https://github.com/Immediate-Mode-UI/Nuklear/assets/1232553/4079df05-e868-4058-8751-f12c2f4948f2)

2023-11-14 07:54 UTC, riri requested changes
LGTM

Be sure to rebase from master to get the latest version then bump the patch version in clib.json.

2023-11-14 08:03 UTC, mackron commented
Cheers. clib.json updated. Was already up to date with master.

2023-11-14 08:09 UTC, riri approved these changes
Ok for me, I let another maintainer reviewing for merging.

2023-11-16 08:10 UTC, merged

2023-11-16 08:10 UTC, RobLoach commented
Good catch.